HOST = "irc.chat.twitch.tv"
PORT = 80
WHISPERHOST = "199.9.253.119"
WHISPERPORT = 443
PASS = "oauth:ayylmao"
IDENT = "nuuls"
CHANNEL = ["nymn_hs", "pajlada", "forsenlol"]
BOTNAMES = ["botnextdoor", "snusbot", "pajbot"]
ADMINS = ["nuuls", IDENT]
EMOTES = ["FeelsGoodMan", "PepeSquare", "PepeCopter", "nymnSmug", "pajaHappy", "FeelsGreatMan"]
